trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Setup SSH Key for GitHub Authentication
- script: |
    mkdir -p ~/.ssh
    echo "$(GIT_SSH_KEY)" | base64 --decode > ~/.ssh/id_ed25519
    chmod 600 ~/.ssh/id_ed25519
    ssh-keyscan github.com >> ~/.ssh/known_hosts
  env:
    GIT_SSH_KEY: $(GIT_SSH_KEY)  # Ensure this secret is added in DevOps Library
  displayName: 'Setup SSH Key'

# Clone Your GitHub Repository Using SSH
- script: |
    git clone git@github.com:munisagar/NodeJsAWSGW.git
  displayName: 'Clone NodeJsAWSGW Repo'

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'
